#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Donatello_FL,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Leonardo_BL,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Chute_Left,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Slides_Left,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     Michelangelo_FR, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     Raphael_BR,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     Chute_Right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     Slides_Right,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    KickStand,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    TubeGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Bucket_Right,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    Bucket_Left,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\Headers\Joystick.h"
#include "..\Headers\Motor.h"
#include "..\Headers\Servo.h"
#include "..\Headers\Global.h"
#include "..\Headers\Drive.h"

//Stores desired motor values
DesiredMotorVals desiredMotorVals;
//Stores desired encoder values
DesiredEncVals desiredEncVals;

void initialize() {
	servoInit();
	motorInit();
	//Initialize to zeroes
	memset(&desiredMotorVals, 0, sizeof(desiredMotorVals));
	memset(&desiredEncVals, 0, sizeof(desiredEncVals));
	clearDebugStream();
}

task main()
{
	initialize();
	joyWaitForStart();
	time1[T1] = 0; //in ms
	driveSetMecMotorN(&desiredMotorVals, 100);
	while (time1[T1] < 2500) {
		motorSetActualPowerToDesired(&desiredMotorVals);
		writeDebugStream("Driving forward!\n");
	}
	driveZeroMecMotor(&desiredMotorVals);
	while (time1[T1] < 10000) {
		motorSetActualPowerToDesired(&desiredMotorVals);
		writeDebugStream("Stopping!\n");
	}
}
