#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Michelangelo_FR, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Donatello_FL,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Raphael_BR,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Leonardo_BL,   tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    Servo_Tube,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Headers\Motor.h"
#include "Headers\Servo.h"
#include "Headers\Drive.h"
#include "Headers\StateMachine.h"

#include "JoystickDriver.c"

/*
Autonomous program chooser (because from past experience it is impossible to choose
on the field).

DEFAULT Do nothing

Prefixes:
  RAMP_ Start from ramp
  FLOOR_ Start from floor

HIT_PARK Hit the stick, park

*/
#define RAMP_HIT_PARK

void initialize() {
	motorInit();
	servoInit();
#ifdef RAMP_HIT_PARK
	//state_RAMP_HIT_PARK_Init();
#endif
}

task main()
{
	initialize();
	StateNames currentState = STATE_BEGIN;
	waitForStart();

	while(currentState != STATE_END) {
		switch(currentState) {

//The only requirement for each state machine is that currentState goes to STATE_END eventually

///////////////////
// RAMP_HIT_PARK //
///////////////////
#ifdef RAMP_HIT_PARK
	case STATE_BEGIN:
		currentState = STATE_END;
		break;
	case STATE_END:
		break;
#endif //RAMP_HIT_PARK



/////////////
// DEFAULT //
/////////////
#ifdef DEFAULT
	case STATE_BEGIN:
		currentState = STATE_END;
		break;
	case STATE_END:
		break;
#endif //DEFAULT

			default:
				//TODO DEBUG invalid state
				break;
		} //switch(currentState)
	} //while(currentState != STATE_END)
}
