#pragma config(UserModel, "Headers/Pragmas.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void explodingSound(){
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundBlip);
		wait10Msec(10);
		PlaySound(soundShortBlip);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundShortBlip);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
}

task main(){
	while(true){
		int nBatteryAverage = nAvgBatteryLevel; //Is an average of nxt reading from last 20 checks
		float nBatAvgVolts = ((float) nBatteryAverage)/1000.0; //convert from milivolts to volts
		int nBatteryLevel = nImmediateBatteryLevel; //Displays the most current nxt battery reading
		float nBatActualVolts = ((float) nBatteryLevel)/1000.0; //Converts the battery reading from milivolts to volts

		float lowNxtPower = 6; //CHANGE THIS WHEN LOW BATTERY LEVEL IS KNOWN

		float extBatAvgVolts = ((float) externalBatteryAvg)/1000.0; //avg external battery average and converts from milivolts to volts
		float extBatActualVolts = ((float) externalBattery)/1000.0; //actual external battery average and converts from milivolts to volts

		float lowExternalPower = 11.5; //CHANGE THIS WHEN LOW BATTERY LEVEL IS KNOWN

		writeDebugStream("NXT batteries: Voltage: %f\n", nBatActualVolts);
		writeDebugStream("Ext batteries: Voltage: %f\n", extBatActualVolts);
		nxtDisplayTextLine(2, "NXT bat (V) %f\n", nBatActualVolts);
		nxtDisplayTextLine(5, "Ext bat (V) %f\n", extBatActualVolts);
		if(nBatAvgVolts < lowNxtPower && nBatActualVolts < lowNxtPower){
			writeDebugStream("Change NXT bat!: V: %f\n", nBatActualVolts);
			nxtDisplayTextLine(2, "Repl NXT bat! (V): %f\n", nBatActualVolts);
			//. -..- .--. .-.. --- -.. .. -. --.
			explodingSound();
		}
		if(extBatAvgVolts < lowExternalPower && extBatActualVolts < lowExternalPower){
			writeDebugStream("Replace external batteries!: Voltage: %f\n", extBatActualVolts);
			nxtDisplayTextLine(5, "Repl ext bat! (V): %f\n", extBatActualVolts);
			//. -..- .--. .-.. --- -.. .. -. --.
			explodingSound();

		}
	wait10MSec(1000);
	clearDebugStream();
	}
}
