#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S3_C1_1,     Michelangelo_FR, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     Donatello_FL,  tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C2_1,     Raphael_BR,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     Leonardo_BL,   tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C3_1,     HarvesterMove, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C3_2,     LiftEncoder,        tmotorTetrix, openLoop, encoder, reversed)
#pragma config(Motor,  mtr_S3_C4_1,     Lift,					 tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C4_2,     Harvester,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    TubeGrabber, 			 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    Bucket,   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo4,        tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/lego-ultrasound.h"

// Give the sensor a nice easy to use name
const tMUXSensor GYRO = msensor_S4_1;
const tMUXSensor HTIRS2 = msensor_S4_4;
const tMUXSensor LEGOUS = msensor_S4_3;

void explodingSound(){
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundBlip);
		wait10Msec(10);
		PlaySound(soundShortBlip);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundShortBlip);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundShortBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
		wait10Msec(10);
		PlaySound(soundBlip);
		PlaySound(soundBlip);
		PlaySound(soundShortBlip);
}

task main(){
	while(true){
		int nBatteryAverage = nAvgBatteryLevel; //Is an average of nxt reading from last 20 checks
		float nBatAvgVolts = ((float) nBatteryAverage)/1000.0; //convert from milivolts to volts
		int nBatteryLevel = nImmediateBatteryLevel; //Displays the most current nxt battery reading
		float nBatActualVolts = ((float) nBatteryLevel)/1000.0; //Converts the battery reading from milivolts to volts

		float lowNxtPower = 6; //CHANGE THIS WHEN LOW BATTERY LEVEL IS KNOWN

		float extBatAvgVolts = ((float) externalBatteryAvg)/1000.0; //avg external battery average and converts from milivolts to volts
		float extBatActualVolts = ((float) externalBattery)/1000.0; //actual external battery average and converts from milivolts to volts

		float lowExternalPower = 11.5; //CHANGE THIS WHEN LOW BATTERY LEVEL IS KNOWN

		writeDebugStream("NXT batteries: Voltage: %f\n", nBatActualVolts);
		writeDebugStream("Ext batteries: Voltage: %f\n", extBatActualVolts);
		nxtDisplayTextLine(2, "NXT bat %f\n", nBatActualVolts);
		nxtDisplayTextLine(5, "Ext bat %f\n", extBatActualVolts);
		if(nBatAvgVolts < lowNxtPower && nBatActualVolts < lowNxtPower){
			writeDebugStream("Change NXT bat!: V: %f\n", nBatActualVolts);
			nxtDisplayTextLine(2, "NXT bat! %f\n", nBatActualVolts);
			//. -..- .--. .-.. --- -.. .. -. --.
			explodingSound();
		}
		if(extBatAvgVolts < lowExternalPower && extBatActualVolts < lowExternalPower){
			writeDebugStream("Replace external batteries!: Voltage: %f\n", extBatActualVolts);
			nxtDisplayTextLine(5, "Ext bat! %f\n", extBatActualVolts);
			//. -..- .--. .-.. --- -.. .. -. --.
			explodingSound();

		}
		wait10Msec(1000);
	}
}
