#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S3_C1_1,     Michelangelo_FR, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     Donatello_FL,  tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C2_1,     Raphael_BR,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     Leonardo_BL,   tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C3_1,     motor0,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C3_2,     Lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C4_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C4_2,     Harvester,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    HarvesterWinch,       tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_4,    HarvesterStop,        tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_5,    TubeGrabber,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    Bucket,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef enum NxtButton {
	LEFT = 2,
	RIGHT = 1,
	ENTER = 3,
	EXIT = 0,
} NxtButton;

task main()
{
	nxtDisplayTextLine(1, "Orange: winch");
	nxtDisplayTextLine(2, "Left/Right: stopper");
	while(true) {
		nxtDisplayTextLine(3, "Stop: %f", ServoValue[HarvesterStop]);
		if (nNxtButtonPressed == LEFT) {
			servo[HarvesterStop] = ServoValue[HarvesterStop] + 15;
			if (servo[HarvesterStop] > 255) {
				servo[HarvesterStop] = 255;
			}
		} else if (nNxtButtonPressed == RIGHT) {
			servo[HarvesterStop] = ServoValue[HarvesterStop] - 15;
			if (servo[HarvesterStop] < 0) {
				servo[HarvesterStop] = 0;
			}
		} else if (nNxtButtonPressed == ENTER) {
			break;
		}
	}
	eraseDisplay();
	nxtDisplayTextLine(1, "Is harvester down completely?");
	wait1Msec(1000);
	while(true) {
		if (nNxtButtonPressed == ENTER) {
			break;
		}
	}
	eraseDisplay();
	nxtDisplayTextLine(1, "Winching...");
	servo[HarvesterWinch] = 255;
	wait1Msec(400);
	servo[HarvesterWinch] = 127;

}
