#pragma config(UserModel, "Headers/Pragmas.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true){
		eraseDisplay();

		if (nNxtButtonPressed == 2) { //left arrow
			motor[HarvesterMove] = -50;
		} else if (nNxtButtonPressed == 1) { //right arrow
			motor[HarvesterMove] = 50;
		} else {
			motor[HarvesterMove] = 0;
		}
		nxtDisplayTextLine(2, "Moving Harvester");
		wait1Msec(100);
	}

}
