#pragma config(Motor,  motorA,          singleMotor,   tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Headers\Data.h"
//#include "Headers\Motor.h"
//#include "Headers\Servo.h"
//#include "Headers\JoyMecanumDrive.h"

//Stores desired motor values
//DesiredMotorVals desiredMotorVals;

void initialize() {
	clearDebugStream();
	//servoInit();
	//motorInit();
	//Initialize to zeroes
	//memset(&desiredMotorVals, 0, sizeof(desiredMotorVals));
}

task main()
{
	initialize();
	waitForStart();
	ClearTimer(T1);
	int time = 30 * 1000; //in ms
	int delay = 50; //ms delay between joystick updates
	int numTJoy = time / delay; //Number of tJoysticks in history
	dataOpenWriteJoyLog(numTJoy);
	while (time1[T1] < time) {
		getJoystickSettings(joystick);
		//joymecdriveSetDesiredPower(&desiredMotorVals, joyGetJoystickPointer());
		//motorSetActualPowerToDesired(&desiredMotorVals);
		motor[singleMotor] = round(((float)joystick.joy1_y1 / 128.0)*100);
		dataWriteJoyLogStream(joystick);
		wait1Msec(delay);
	}
	dataCloseJoyLog();
}
