#pragma config(UserModel, "Headers/Pragmas.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Headers\Global.h"
#include "Headers\Motor.h"
#include "Headers\Servo.h"
#include "Headers\JoyMecanumDrive.h"
#include "Headers\JoyAuxiliary.h"
#include "Headers\JoyPlayMusic.h"

#include "Headers\Data.h"

//Stores desired motor values
//DesiredMotorVals desiredMotorVals;
//Stores desired encoder values
//DesiredEncVals desiredEncVals;

void initialize() {
	clearDebugStream();
	writeDebugStream("This is JoyRecord\n");
	//Initialize to zeroes
//	memset(&desiredMotorVals, 0, sizeof(desiredMotorVals));
//	memset(&desiredEncVals, 0, sizeof(desiredEncVals));
//	motorInit();
//	servoInit();

}

/*void callAuxiliaryMotors(){
	joyLift(&desiredMotorVals, joyGetJoystickPointer());
	joyHarvester(&desiredMotorVals, joyGetJoystickPointer());
	joyBucketDrop(&desiredMotorVals, joyGetJoystickPointer());
}*/

task main()
{
	initialize();
	joyWaitForStart();
	long pgmStartTimeMs = nPgmTime;

	int timeLengthMs = 5 * 1000; //leave time to close file at the end
	int delay = 50; //ms delay between joystick updates
	int numTJoy = timeLengthMs / delay; //Number of tJoysticks in history

	short fileSize = numTJoy * TJOY_SIZE;
	TFileHandle fileHandle;
	string fileName = JOY_LOGFILE;

	dataOpenWrite(&fileHandle, fileName, fileSize);

	while ((nPgmTime - pgmStartTimeMs) < timeLengthMs) {
		joyUpdateJoystickSettings();
		//joymecdriveSetDesiredPower(&desiredMotorVals, joyGetJoystickPointer());
		//callAuxiliaryMotors();
		//motorSetActualPowerToDesired(&desiredMotorVals);
		TJoystick *joystickPtr = joyGetJoystickPointer();
		joyplaymusicPlay(joystickPtr);

		byte buffer[TJOY_SIZE];
		memcpy(buffer, joystickPtr, TJOY_SIZE);

		dataWriteBytes(&fileHandle, buffer, TJOY_SIZE);
		wait1Msec(delay);
	}

	dataClose(&fileHandle);
}
