#pragma config(UserModel, "Headers/Pragmas.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LIFT_POWER 30

task main(){
	nMotorEncoder[Lift] = 0;
	while(true){
		eraseDisplay();

		if (nNxtButtonPressed == 2) { //left arrow
			motor[Lift] = -LIFT_POWER;
		} else if (nNxtButtonPressed == 1) { //right arrow
			motor[Lift] = LIFT_POWER;
		} else {
			motor[Lift] = 0;
		}
		nxtDisplayTextLine(2, "Power: %f", motor[Lift]);
		nxtDisplayTextline(4, "Encoder: %d", nMotorEncoder[Lift]);
		wait1Msec(100);
	}
}
