#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Michelangelo_FR, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Donatello_FL,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Raphael_BR,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Leonardo_BL,   tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//If none of these work, I will be very sad.
#define TOTAL_MOTORS kNumbOfTotalMotors
//#define TOTAL_MOTORS kNumbOfRealMotors
//#define TOTAL_MOTORS kNumbOfVirtualMotors


task main()
{
		for(int i=0;i<TOTAL_MOTORS;i++) {
			motor[i] = 50;
		}
		wait1Msec(2000);
		motor[Michelangelo_FR] = 0;
		motor[Donatello_FL] = 0;
		motor[Raphael_BR] = 0;
		motor[Leonardo_BL] = 0;
}
