#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		motor[leftMotor] =100;
		motor[rightMotor] = -100;
		wait1Msec(1000);
		for(int i=0;i<kNumbOfRealMotors;i++) {
			motor[i] = 0;
		}
}
