#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S3_C1_1,     Michelangelo_FR, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     Donatello_FL,  tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C2_1,     Raphael_BR,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     Leonardo_BL,   tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S3_C3_1,     HarvesterMove, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C3_2,     motor0,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C4_1,     Lift,					 tmotorTetrix, openLoop, encoder, reversed)
#pragma config(Motor,  mtr_S3_C4_2,     Harvester,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4, 			 tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    TubeGrabber,   tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    Bucket,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/lego-ultrasound.h"

// Give the sensor a nice easy to use name
const tMUXSensor GYRO = msensor_S4_1;
const tMUXSensor HTIRS2 = msensor_S4_4;
const tMUXSensor LEGOUS = msensor_S4_3;

#include "Headers\Joystick.h"
#include "Headers\Motor.h"
#include "Headers\Servo.h"
#include "Headers\Global.h"
#include "Headers\Drive.h"
#include "Auton\Auton.h"

//ALL states for center Tube Autonomous
typedef enum CenterTubeStates {
	STATE_START, //
	STATE_DRIVETOWARDCENTERPIECE, //
	STATE_DETECTIR,
	STATE_ORBITTOCENTERGOAL,//
	STATE_DROPBUCKET, //
	STATE_DRIVERIGHT, //
	STATE_KICKSTAND, //
	STATE_WAITFORLIFT,
	STATE_END,
	STATE_SHORTBUCKET,
	STATE_CLOSEBUCKET,
} CenterTubeStates;

static CenterTubeStates currentState = STATE_START;

//States for center position
typedef enum CenterPos {
	HORIZ_TO_PARK,
	ANGLE_TO_PARK,
	VERT_TO_PARK,
} CenterPos;

//IR Sensor
int dirEnh, strEnh = 0; //direction, strength enhanced

task main()
{
	//SLIDE SIDE IS FACING DOWN THE RAMP
	CenterPos centerPos;
	bool end = false;
	bool init = true;

	initialize();
	writeDebugStream("This is CenterTubeIR\n");
	waitForStart();

	while(!end){
		long loopStartTimeMs = nPgmTime;
		if (rest) {
			writeDebugStream("Resting!\n");
			motorLimitDesiredPowerToEncoder(&desiredMotorVals, &desiredEncVals);
			motorSetActualPowerToDesired(&desiredMotorVals);
			motorUpdateState();
			if (nPgmTime - restStartTimeMs > 2000) {
				rest = false;
				restStartTimeMs = 0;
			}
		} else {
			switch(currentState){
				case STATE_START:
					currentState = STATE_DRIVETOWARDCENTERPIECE;
					break;
				case STATE_DRIVETOWARDCENTERPIECE:
					writeDebugStream("State: Drive Toward Centerpiece\n");
					/*
					motorUpdateState();

					motor[Lift] = LIFT_DOWN;

					if (motorGetEncoder(Lift) <= -SIXTY_GOAL) {
						motor[Lift] = 0;
					}

					motor[MecMotor_FL] = 100;
					motor[MecMotor_BL] = 100;
					motor[MecMotor_FR] = 100;
					motor[MecMotor_BR] = 100;

					if (motorGetEncoder((tMotor)MecMotor_FL) < 1000) {
						motor[Lift] = 0;
						restMecMotors();
						currentState = STATE_DETECTIR;
					}*/

					break;
				case STATE_DETECTIR:
					writeDebugStream("State: Detect IR\n");
					//Read average of 10 values
					long sum = 0;
					for (int i=0; i<10; i++) {
						HTIRS2readEnhanced(HTIRS2, dirEnh, strEnh);
						sum += strEnh;
					}
					long avgStrEnh = sum / 10;

					writeDebugStream("IR Str Enh: %d\n", avgStrEnh);

					if (avgStrEnh > 90) {
						writeDebugStream("Detected vertical to park\n");
						centerPos = VERT_TO_PARK;
					} else if (avgStrEnh > 40) {
						writeDebugStream("Detected angle to park\n");
						centerPos = ANGLE_TO_PARK;
					} else {
						writeDebugStream("Detected horizontal to park\n");
						centerPos = HORIZ_TO_PARK;
					}

					if (centerPos == VERT_TO_PARK) {
						currentState = STATE_WAITFORLIFT;
					} else {
						currentState = STATE_ORBITTOCENTERGOAL;
					}
					break;
			case STATE_ORBITTOCENTERGOAL:
					writeDebugStream("State: Orbit to center goal\n");
					/*
					motorUpdateState();

					motor[Lift] = -100;

					if (motorGetEncoder(Lift) <= -LIFT_MAX) {
						motor[Lift] = 0;
					}

					driveSetMecMotorPolarDegrees(&desiredMotorVals, 315, 1.0, 0.5);
					motor[MecMotor_FL] = desiredMotorVals.power[MecMotor_FL];
					motor[MecMotor_BL] = desiredMotorVals.power[MecMotor_BL];
					motor[MecMotor_FR] = desiredMotorVals.power[MecMotor_FR];
					motor[MecMotor_BR] = desiredMotorVals.power[MecMotor_BR];

					if (centerPos == ANGLE_TO_PARK) {
						if (motorGetEncoder((tMotor)MecMotor_FL) < 2000) {
							restMecMotors();
							currentState = STATE_WAITFORLIFT;
						}
					} else if (centerPos == HORIZ_TO_PARK) {
						if (motorGetEncoder((tMotor)MecMotor_FL) < 3000) {
							restMecMotors();
							currentState = STATE_WAITFORLIFT;
						}
					}*/
					break;
				case STATE_WAITFORLIFT:
					writeDebugStream("State: WAIT FOR LIFT\n");
					/*
					motorUpdateState();

					motor[Lift] = LIFT_DOWN;

					if (motorGetEncoder(Lift) <= -LIFT_MAX) {
						motor[Lift] = 0;
						restMecMotors();
						currentState = STATE_DROPBUCKET;
					}*/
					break;
				case STATE_DROPBUCKET:
					writeDebugStream("State: Drop Bucket\n");
					/*
					servoSetNonCont(Bucket, servoDefinitions[Bucket].minValue);

					restMecMotors();
					currentState = STATE_CLOSEBUCKET;*/
					break;
				case STATE_CLOSEBUCKET:
					writeDebugStream("State: Close bucket\n");
					/*servoSetNonCont(Bucket, servoDefinitions[Bucket].maxValue);

					restMecMotors();

					currentState = STATE_DRIVERIGHT;*/
					break;
				case STATE_DRIVERIGHT:
					writeDebugStream("State: Drive Right Toward Kickstand\n");
					/*
					motorUpdateState();

					motor[Lift] = 15;

					if (motorGetEncoder(Lift) >= 500) {
						motor[Lift] = 0;
					}

					motor[MecMotor_FL] = 100;
					motor[MecMotor_BL] = -100;
					motor[MecMotor_FR] = -100;
					motor[MecMotor_BR] = 100;

					if (motorGetEncoder((tMotor) MecMotor_FL) > 2000) {
						restMecMotors();
						currentState = STATE_KICKSTAND;
					}*/

					break;
				case STATE_KICKSTAND:
					writeDebugStream("State: Drive Kickstand\n");
					/*motor[Lift] = 15;

					if (motorGetEncoder(Lift) >= 500) {
						motor[Lift] = 0;
					}

					motor[MecMotor_FL] = 100;
					motor[MecMotor_BL] = 100;
					motor[MecMotor_FR] = 100;
					motor[MecMotor_BR] = 100;

					if (motorGetEncoder((tMotor)MecMotor_FL) > 2000) {
						restMecMotors();
						currentState = STATE_END;
					}*/

					break;
				case STATE_END:
					/*motor[Lift] = 15;

					if (motorGetEncoder(Lift) >= 500) {
						motor[Lift] = 0;
						end = true;
					}*/
					break;
			} //switch
		} //if
	//writeDebugStream("DMV: %d %d %d %d\n", desiredMotorVals.power[MecMotor_FL], desiredMotorVals.power[MecMotor_BL], desiredMotorVals.power[MecMotor_FR], desiredMotorVals.power[MecMotor_BR]);
	//writeDebugStream("VIRTENC: %d %d %d %d\n", motorGetEncoder((tMotor) MecMotor_FL), motorGetEncoder((tMotor) MecMotor_BL), motorGetEncoder((tMotor) MecMotor_FR), motorGetEncoder((tMotor) MecMotor_BR);
	//writeDebugStream("REALENC: %d %d %d %d\n", nMotorEncoder[Donatello_FL], nMotorEncoder[Leonardo_BL], nMotorEncoder[Michelangelo_FR], nMotorEncoder[Raphael_BR]);
	//writeDebugStream("Full auton loop took: %d ms\n", nPgmTime - loopStartTimeMs);
	} //while

/*	driveSetEncoderN(&desiredEncVals, ######);
	driveSetEncoderW(&desiredEncVals, ######);
	driveSetEncoderN(&desiredEncVals, ######);
	servoSetNonCont(Wing_Base, servoDefinitions[Wing_Base].minValue);
	driveSetEncoderS(&desiredEncVals, ######);
	desiredMotorVals->power[Wing_Middle] = -100;
	time[T1] = 0;
	while (time[T1] < 200){
		motorSetActualPowerToDesired(&desiredMotorVals);
	}
	desiredMotorVals->power[Wing_Middle] = 0;
	motorSetActualPowerToDesired(&desiredMotorVals);
	driveSetEncoderW(&desiredEncVals, ######);
	driveSetEncoderS(&desiredEncVals, ######);
	driveSetEncoderW(&desiredEncVals, ######); */
}
