#pragma config(UserModel, "Headers/Pragmas.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Headers\Global.h"
#include "Headers\Motor.h"
#include "Headers\Servo.h"
#include "Headers\JoyMecanumDrive.h"
#include "Headers\JoyAuxiliary.h"

//Stores desired motor values
DesiredMotorVals desiredMotorVals;
//Stores desired encoder values
DesiredEncVals desiredEncVals;

void initialize() {
	clearDebugStream();
	writeDebugStream("This is TeleOp.c\n");
	initSensor(&irSeeker, HTIRS2);
	initSensor(&gyroSensor, GYRO);
	sensorCalibrate(&gyroSensor);

	//Initialize to zeroes
	memset(&desiredMotorVals, 0, sizeof(desiredMotorVals));
	memset(&desiredEncVals, 0, sizeof(desiredEncVals));
	motorInit(&desiredEncVals);
	servoInit();
}

void callAuxiliaryMotors(){
	joyLift(&desiredMotorVals, &desiredEncVals, joyGetJoystickPointer());
	joyHarvester(&desiredMotorVals, joyGetJoystickPointer());
	joyGrabber(&desiredMotorVals, joyGetJoystickPointer());
	joyBucketDrop(&desiredMotorVals, joyGetJoystickPointer());
}

task main() {
	initialize();
	joyWaitForStart();

	while (true) {
		long loopStartTimeMs = nPgmTime;

		joyUpdateJoystickSettings();
		joymecdriveSetDesiredPower(&desiredMotorVals, joyGetJoystickPointer());
		//joymecdriveDebug(&desiredMotorVals, &desiredEncVals, joyGetJoystickPointer());
		callAuxiliaryMotors();
		motorLimitDesiredPowerToEncoder(&desiredMotorVals, &desiredEncVals);
		motorSetActualPowerToDesired(&desiredMotorVals);
		motorUpdateState();
		//joyAuxDebug(&desiredMotorVals, joyGetJoystickPointer());


		//IR code
		readSensor(&irSeeker);

		writeDebugStream("IR reads: ");
		writeDebugStream("DC: %d AC: %d\n", irSeeker.dcDirection, irSeeker.acDirection);
		writeDebugStream("D: %d %d %d %d %d\n", irSeeker.dcValues[0], irSeeker.dcValues[1],
			irSeeker.dcValues[2], irSeeker.dcValues[3], irSeeker.dcValues[4]);
		writeDebugStream("A: %d %d %d %d %d\n", irSeeker.acValues[0], irSeeker.acValues[1],
			irSeeker.acValues[2], irSeeker.acValues[3], irSeeker.acValues[4]);
		writeDebugStream("Enh Dir: %d Str %d\n", irSeeker.enhDirection, irSeeker.enhStrength);


		//ULTRA code
		int ultraDistance = 0;
		ultraDistance = USreadDist(LEGOUS);
		writeDebugStream("Dist:  %3d cm\n", ultraDistance);


		//GYRO code
		readSensor(&gyroSensor);
    writeDebugStream("Offset: %4f", gyroSensor.offset);
    writeDebugStream("Gyro:   %4f", gyroSensor.rotation);



		writeDebugStream("DMV: %d %d %d %d\n", desiredMotorVals.power[MecMotor_FL], desiredMotorVals.power[MecMotor_BL],
			desiredMotorVals.power[MecMotor_FR], desiredMotorVals.power[MecMotor_BR]);
		writeDebugStream("Full teleop loop took: %d ms\n", nPgmTime - loopStartTimeMs);

	}
}
